### ISSUE TITLE
-42 au projet 

### ISSUE THREAD

**Issue by Noubouille** [RomainFlori/My_malloc#1]
j'ai eu -42 au projet à cause du git clone à cause de toi 😡

**Comment by RomainFlori** [comment]
Il ne faut pas git clone le projet... c'est juste une aide pour la communauté d'Epitech durant ces mois difficiles de Covid-19

**Comment by Noubouille** [comment]
> Il ne faut pas git clone le projet... c'est juste une aide pour la communauté d'Epitech durant ces mois difficiles de Covid-19

c'est vrai merci le sang de la veine

**Comment by fieu** [comment]
c'est chaud tout ca
